from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 initial=True
 dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
 migrations.CreateModel(name='Course',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('code',models.CharField(blank=True,max_length=30)),('credit',models.DecimalField(decimal_places=1,default=3,max_digits=4)),('color',models.CharField(default='#7c5cff',max_length=7)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
 migrations.CreateModel(name='Note',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('content',models.TextField()),('note_date',models.DateField()),('updated_at',models.DateTimeField(auto_now=True)),('course',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='notes',to='hub.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
 migrations.CreateModel(name='Task',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('due_date',models.DateField(blank=True,null=True)),('period',models.CharField(choices=[('daily','Daily'),('weekly','Weekly'),('monthly','Monthly')],default='weekly',max_length=10)),('priority',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High')],default='medium',max_length=10)),('completed',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('course',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='tasks',to='hub.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
 migrations.CreateModel(name='Topic',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('details',models.TextField(blank=True)),('completed',models.BooleanField(default=False)),('position',models.PositiveIntegerField(default=0)),('course',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='topics',to='hub.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))],options={'ordering':['position','id']}),
 migrations.CreateModel(name='GradeComponent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('label',models.CharField(max_length=80)),('maximum',models.DecimalField(decimal_places=2,max_digits=6)),('score',models.DecimalField(blank=True,decimal_places=2,max_digits=6,null=True)),('course',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='components',to='hub.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))],options={'unique_together':{('course','label')}}),
 migrations.CreateModel(name='Event',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('starts_at',models.DateTimeField()),('event_type',models.CharField(choices=[('exam','Exam'),('assignment','Assignment'),('presentation','Presentation'),('study','Study session'),('personal','Personal')],default='study',max_length=15)),('details',models.TextField(blank=True)),('course',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='events',to='hub.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))],options={'ordering':['starts_at']}),
 migrations.CreateModel(name='StudyFile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('file',models.FileField(upload_to='study_files/%Y/%m/')),('uploaded_at',models.DateTimeField(auto_now_add=True)),('course',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='files',to='hub.course')),('note',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='files',to='hub.note')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
 migrations.CreateModel(name='UserPreference',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('theme',models.CharField(default='dark',max_length=10)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='preference',to=settings.AUTH_USER_MODEL))])]
